/** Testi di default per tutti i tooltip della scheda evento — se un
 *  admin ne personalizza uno dalla sezione Sistema → Testi tooltip,
 *  quello scritto lì sostituisce il default qui sotto (stesso sistema
 *  già usato per i testi configurabili della homepage: la tabella
 *  "contenuti", chiave prefissata "tooltip_" per non confondersi con
 *  gli altri contenuti del sito). Se non è mai stato personalizzato,
 *  si vede semplicemente questo testo qui.
 *
 *  Un'unica lista, così sia la scheda evento che la schermata di
 *  modifica in Sistema partono dagli stessi identici valori — nessuna
 *  duplicazione tra "cosa mostro" e "cosa posso modificare". */
export const TOOLTIP_DEFAULT: Record<string, string> = {
  categoria: 'I pulsanti in alto sul sito.',
  url: 'Facoltativo — se lo lasci vuoto, si genera da solo.',
  avviso_disponibilita: 'Mostrato ai clienti al posto dei posti reali. Lasciandolo su "Automatico", il sito mostra da solo "Pochi posti" (sotto il 20% rimasto) o "Posti terminati" quando serve, senza che tu debba pensarci — scegli una delle altre opzioni solo se vuoi forzarla tu (es. per una promozione), a prescindere dai numeri reali.',
  tragitti: 'Facoltativi — puoi aggiungerli anche dopo. Qui censisci solo il nome e la sequenza di fermate: orario, prezzo, posti e il primo bus si confermano poi in Partenze, non qui — un tragitto non è in vendita finché non lo confermi lì.',
  informazioni_viaggio: 'Mostrate sulla pagina dell\'evento, sotto la foto.',
  descrizione_evento: 'Visibile ai clienti sulla pagina, e usata anche per Google/social. Diversa dalle "Informazioni viaggio" sopra: questa è un testo più discorsivo su evento/artista, quella sopra è pratica (ritrovo, regole del bus, ecc.).',
  cosa_incluso: 'Mostrato sempre in evidenza nella pagina evento, non nascosto in un accordion — es. "Viaggio A/R, posto assegnato". Chiarisci anche cosa NON è incluso (es. il biglietto d\'ingresso), se può generare dubbi.',
  requisiti_evento: 'Mostrato sempre in evidenza nella pagina evento — limiti d\'età, condizioni fisiche richieste, o qualunque altra restrizione che il cliente deve sapere PRIMA di prenotare, non dopo.',
  immagine_intestazione: 'Facoltativa — compare come fascia in cima al biglietto (larga quanto la pagina, ritagliata automaticamente).',
  visibile_sito: 'Se lo disattivi, l\'evento non compare mai sul sito (anche se è nel futuro). Gli eventi con data già passata comunque non compaiono più sul sito, a prescindere da questo interruttore.',
  variazioni_intro: 'Cambi di data, luogo, fermate o orari su viaggi già venduti: qui vedi quali clienti sono stati avvisati e come hanno risposto.',
  cestino_intro: 'Niente viene mai cancellato per davvero — se ha prenotazioni collegate, andrebbero perse. Qui trovi tutto quello che hai eliminato, sempre recuperabile.',
  fermate_intro: 'L\'anagrafica dei luoghi fisici — si scelgono da qui componendo i tragitti di un evento, invece di riscrivere ogni volta città e indirizzo.',
  ruoli_intro: 'Puoi creare ruoli con il nome che preferisci e scegliere esattamente cosa può fare chi lo ha. Puoi assegnare solo i permessi che possiedi tu stesso.',
  comunicazioni_intro: 'Scegli l\'evento per cui vuoi scrivere ai clienti — poi filtri per servizio, tratta o fermata specifica.',
  layout_biglietto_intro: 'Trascina ogni sezione dove vuoi sul biglietto; trascina l\'angolo in basso a destra per ridimensionarla — mentre trascini, delle linee rosa ti avvisano quando ti allinei con un altro elemento o con centro/bordi della pagina, e ci si "aggancia" da sole per allineamenti sempre precisi. Ogni evento usa il layout predefinito a meno che, dalla sua scheda, tu non ne scelga uno diverso.',
  template_email_intro: 'Modifica il testo che i clienti ricevono via email. I segnaposto tra doppie graffe (es. {{nome}}) vengono sostituiti automaticamente con il dato vero al momento dell\'invio — non toglierli, altrimenti quel punto resterebbe vuoto.',
  white_label_intro: 'Ogni riga collega un organizzatore a UN suo evento specifico — il widget che riceve serve solo a vendere il viaggio di quell\'evento, mai altro.',
  offerte_intro: 'Crea un link con uno sconto percentuale dedicato per una campagna pubblicitaria (es. "-20%" per chi arriva da Meta) — si applica al prezzo normale di qualunque fermata scelga il cliente. Il link pubblico porta solo un nome, mai lo sconto: non è modificabile dal browser.',
  tourleader_censisci_intro: 'Registra qui direttamente un tour leader che conosci già — non deve passare dal modulo pubblico di autocandidatura. Parte come "Attivo", puoi cambiare stato in qualsiasi momento dall\'elenco.',
  permessi_personali_intro: 'Clicca un permesso per aggiungerlo o toglierlo solo per questa persona, indipendentemente dal ruolo. Puoi togliere qualsiasi permesso, ma puoi concederne in più solo tra quelli che possiedi tu stesso.',
  // Una spiegazione per ogni voce di Partenze: prima Orari e Prezzi
  // mostravano il testo dei preventivi, e Preventivi uno generico.
  partenze_orari_intro: 'Calcola l\'orario di ogni fermata partendo dall\'arrivo ed esporta l\'elenco da mandare ai fornitori. Ogni card è un evento.',
  partenze_preventivi_intro: 'Chiedi un preventivo ai fornitori vicini, oppure registra quello avuto per telefono o email, poi accetta il migliore.',
  partenze_prezzi_intro: 'Dal costo del preventivo calcola il prezzo di ogni fermata, controllalo e metti il tragitto in vendita.',
  partenze_da_confermare_intro: 'Tragitti già in vendita: quando le prenotazioni coprono il costo, crea la linea e assegna i bus.',
  partenze_confermate_intro: 'Tragitti con almeno un bus assegnato. In rosso quelli con più passeggeri che posti.',
  partenze_passate_intro: 'Archivio degli eventi già passati, qualunque fosse lo stato.',
  preventivo_form_intro: 'Costo e posti arrivano dal preventivo registrato in Preventivi. Il prezzo di ogni fermata cresce con i km fino all\'arrivo: puoi correggerlo prima di salvare.',
  layout_biglietto_campo: 'Composizione grafica del PDF (ordine sezioni, posizione QR) — si gestiscono da Marketing → Layout biglietto.',
  immagini_evento_intro: 'Carica un\'immagine, oppure incolla il link se è già online da qualche parte — vengono mostrate nella galleria della pagina evento sul sito.',
  biglietto_grafica_intro: 'Grafica del biglietto digitale — facoltativa, se non la imposti il PDF (con QR) usa l\'aspetto di base.',
  fermata_nome_campo: 'es. "Milano Lambrate", non solo "Milano".',
  fermata_link_campo: 'Facoltativo — es. Google Maps, punto di ritrovo.',
  fermate_orario_intro: 'Orari, prezzi e posti delle fermate si impostano da Partenze: gli orari si calcolano partendo dall\'arrivo indicato qui sopra.',
  coupon_promoter_campo: 'Chi usa questo coupon fa guadagnare la commissione a questo promoter, insieme allo sconto per il cliente — un solo codice per entrambe le cose.',
  coupon_compenso_campo: 'Il compenso per QUESTO codice specifico — se non imposti nulla, si usa il tasso di default dell\'account del promoter (impostato nella sua scheda).',
  voucher_cliente_campo: 'Se assegni un voucher a un cliente, solo lui (stessa email) potrà usarlo — nessun altro, anche conoscendo il codice. Potrai anche mandarglielo via email, e lui lo vedrà nel suo account.',
  voucher_invia_email_campo: 'Manda il codice via email al cliente assegnato, con lo sconto e la scadenza — puoi rimandarla quante volte vuoi.',
  tour_descrizione_campo: 'Visibile ai clienti sulla pagina del tour, sotto il sottotitolo — una presentazione dello spettacolo, valida per tutte le date insieme.',
  tour_descrizione_seo_campo: 'Usata per Google/social al posto della descrizione automatica. Se la lasci vuota, si genera da sola.',
  tour_date_campo: 'Non serve che siano consecutive, né nello stesso mese — scegli tra gli eventi già esistenti.',
};

/** Etichette leggibili per la schermata di modifica in Sistema — non
 *  serve che l'admin capisca la chiave tecnica ("avviso_disponibilita"),
 *  gli si mostra questa invece. */
export const TOOLTIP_ETICHETTA: Record<string, string> = {
  categoria: 'Categoria (scheda evento)',
  url: 'URL (scheda evento)',
  avviso_disponibilita: 'Avviso disponibilità (scheda evento)',
  tragitti: 'Tragitti (scheda evento)',
  informazioni_viaggio: 'Informazioni viaggio (scheda evento)',
  descrizione_evento: 'Descrizione evento (scheda evento)',
  cosa_incluso: 'Cosa è incluso (scheda evento)',
  requisiti_evento: 'Requisiti e restrizioni (scheda evento)',
  immagine_intestazione: 'Immagine di intestazione (scheda evento)',
  visibile_sito: 'Visibile sul sito (scheda evento)',
  variazioni_intro: 'Introduzione (sezione Variazioni)',
  cestino_intro: 'Introduzione (sezione Cestino)',
  fermate_intro: 'Introduzione (sezione Fermate)',
  ruoli_intro: 'Introduzione (sezione Ruoli)',
  comunicazioni_intro: 'Introduzione (sezione Comunicazioni)',
  layout_biglietto_intro: 'Introduzione (sezione Layout biglietto)',
  template_email_intro: 'Introduzione (sezione Testo email)',
  white_label_intro: 'Introduzione (sezione White Label)',
  offerte_intro: 'Introduzione (tab Offerte, dentro un evento)',
  tourleader_censisci_intro: 'Introduzione (modulo "Censisci tour leader")',
  permessi_personali_intro: 'Introduzione (modulo "Permessi personali", dentro Amministratori)',
  partenze_orari_intro: 'Introduzione (Partenze → Orari)',
  partenze_preventivi_intro: 'Introduzione (Partenze → Preventivi)',
  partenze_prezzi_intro: 'Introduzione (Partenze → Prezzi)',
  partenze_da_confermare_intro: 'Introduzione (Partenze → Da confermare)',
  partenze_confermate_intro: 'Introduzione (Partenze → Confermate)',
  partenze_passate_intro: 'Introduzione (Partenze → Passate)',
  preventivo_form_intro: 'Prezzi di vendita (Partenze → Prezzi, dentro un tragitto)',
  layout_biglietto_campo: 'Layout del biglietto (scheda evento)',
  immagini_evento_intro: 'Introduzione (tab Immagini, scheda evento)',
  biglietto_grafica_intro: 'Introduzione (tab Biglietto, scheda evento)',
  fermata_nome_campo: 'Nome (sezione Fermate)',
  fermata_link_campo: 'Link (sezione Fermate)',
  fermate_orario_intro: 'Introduzione (elenco fermate, scheda evento)',
  coupon_promoter_campo: 'Assegna a un promoter (sezione Coupon)',
  coupon_compenso_campo: 'Compenso per il codice (sezione Coupon)',
  voucher_cliente_campo: 'Assegna a un cliente (sezione Voucher)',
  voucher_invia_email_campo: 'Invia via email (sezione Voucher)',
  tour_descrizione_campo: 'Descrizione (sezione Tour)',
  tour_descrizione_seo_campo: 'Descrizione SEO (sezione Tour)',
  tour_date_campo: 'Date da raggruppare (sezione Tour)',
};
