import type { SezioneGestionale } from './AdminLayout';

// Permesso richiesto per ogni sezione, usato per bloccare l'accesso
// diretto (non solo nascondere la voce di menu) se qualcuno perde un
// permesso mentre è già loggato. Le Statistiche lo usano anche per
// mostrare "Apri →" solo verso le sezioni che l'amministratore può vedere.
export const PERMESSO_SEZIONE: Record<SezioneGestionale, string> = {
  statistiche: 'statistiche.visualizza',
  eventi: 'eventi.visualizza',
  bundle: 'bundle.visualizza',
  tour: 'tour.visualizza',
  vetrina: 'eventi.vetrina',
  calendario: 'eventi.calendario',
  cestino: 'eventi.cestino',
  transazioni: 'prenotazioni.transazioni',
  pagamenti: 'prenotazioni.pagamenti',
  rimborsi: 'prenotazioni.pagamenti',
  variazioni: 'prenotazioni.pagamenti',
  utenti: 'utenti.visualizza',
  fornitori: 'fornitori.visualizza',
  fermate: 'tragitti.visualizza',
  tragitti: 'tragitti.visualizza',
  promoter: 'promoter.visualizza',
  organizzatori: 'organizzatori.visualizza',
  'white-label': 'white-label.visualizza',
  tourleader: 'tourleader.visualizza',
  coupon: 'coupon.visualizza',
  voucher: 'coupon.visualizza',
  campagne: 'campagne.gestisci',
  'lista-attesa': 'eventi.partenze',
  offerte: 'offerte.gestisci',
  chat: 'chat.visualizza',
  comunicazioni: 'eventi.crea',
  contenuti: 'pagine.gestisci',
  amministratori: 'utenze.gestisci',
  ruoli: 'permessi.gestisci',
  'testi-tooltip': 'impostazioni.gestisci',
  'partenze-orari': 'eventi.partenze',
  'partenze-preventivi': 'eventi.partenze',
  'partenze-prezzi': 'eventi.partenze',
  'partenze-da-confermare': 'eventi.partenze',
  'partenze-confermato': 'eventi.partenze',
  'partenze-passate': 'eventi.partenze',
  linee: 'eventi.partenze',
  impostazioni: 'impostazioni.gestisci',
  tracciamento: 'impostazioni.gestisci',
  'template-email': 'template-email.gestisci',
  'layout-biglietto': 'layout-biglietto.gestisci',
  'beta-tragitti-vicini': 'eventi.partenze',
};
